[package]
name = "harper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
base64 = "0.22.1"
chrono = "0.4.40"
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
env_logger = "0.11.7"
json = "0.12.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
hickory-resolver = {  version = "0.24.4" , features = ["dnssec-ring"] }
tldextract = "0.6.0"
url = "2.5.4"
tokio = { version = "1.44.1", features = ["fs", "macros"] }
reqwest = "0.12.15"
directories = "6.0.0"
indicatif = "0.17.11"
