[package]
name = "harper"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.40"
clap = { version = "4.5.29", features = ["derive"] }
json = "0.12.4"
nucleo = "0.5.0"
tldextract = "0.6.0"
url = "2.5.4"
