[package]
name = "harper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["clock"], default-features = false }
clap = { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
env_logger = { version = "0.11.11", default-features = false }
json = "0.12.4"
serde = { version = "1.0.229", features = ["serde_derive"], default-features = false }
serde_json = "1.0.151"
hickory-resolver = "0.26.1"
tldextract = { git = "https://github.com/peterc-s/tldextract-rs", tag = "0.6.1" }
url = { version = "2.5.8", default-features = false }
tokio = { version = "1.53.1", features = ["fs"] }
reqwest = { version = "0.13.4", features = ["default-tls"], default-features = false }
directories = "6.0.0"
indicatif = { version = "0.18.6", default-features = false }

[lints.rust]
# Error on warning
warnings = { level = "deny", priority = -1 }

# Allow tarpaulin_include
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

# Basic good practices
non_ascii_idents = "forbid"
unsafe_code = "warn"

# Other opinionated lints
macro_use_extern_crate = "deny"
absolute_paths_not_starting_with_crate = "deny"
explicit_outlives_requirements = "warn"
missing_abi = "deny"
single_use_lifetimes = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
meta_variable_misuse = "warn" # may have false positives
keyword_idents_2024 = "warn"
missing_docs = "allow"
redundant_lifetimes = "warn"
unit_bindings = "warn"
trivial_casts = "warn" # may have false positives
trivial_numeric_casts = "warn"
unsafe_attr_outside_unsafe = "warn"
unused_import_braces = "warn"
variant_size_differences = "warn" # should be assessed case-by-case

[lints.clippy]
# cargo = { level = "warn", priority = -1 }
wildcard_dependencies = "warn"
# cargo_common_metadata = "warn"
multiple_crate_versions = "allow"

allow_attributes = "warn"
clone_on_ref_ptr = "warn"
implicit_clone = "warn"
create_dir = "warn"
dbg_macro = "warn"
exit = "warn"
undocumented_unsafe_blocks = "warn"
unused_result_ok = "warn"
unused_trait_names = "warn"
unwrap_used = "warn"
# expect_used = "warn" # may turn off if this becomes an issue

# Nursery
nursery = { level = "warn", priority = -1 }
missing_const_for_fn = "allow" # const still being worked on so may give false positives

# Pedantic
pedantic = { level = "warn", priority = -1 }
cast_precision_loss = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
struct_excessive_bools = "allow"

