[package]
name = "harper"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.40"
clap = { version = "4.5.29", features = ["derive"] }
hickory-resolver = {  version = "0.24.4" , features = ["dnssec-ring"] }
json = "0.12.4"
tldextract = "0.6.0"
url = "2.5.4"
